config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  # Feedback
  resources :questions
  resources :answers, only: [:index, :create, :update]

  # Noice Sessions
  resources :noice_sessions

  scope 'admin' do
    resources :tags
  end

  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'content', to: 'pages#content', as: :content
  get 'events', to: 'pages#events', as: :events
  get 'search', to: 'pages#search', as: :search

  root to: redirect("http://unbouncepages.com/mynoice/")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
   dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form_errors.html.slim
#error_explanation
  p.lead
    = pluralize(model.errors.count, "error")
    |  prohibited this from being saved:
  ul.list-group
    - model.errors.full_messages.each do |message|
      li.list-group-item
        = message

app/views/application/_header.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-primary
  / Brand
  - brand_path = user_signed_in? ? dashboard_path : root_path
  = link_to brand_path, class: "navbar-brand btn btn-outline-light" do
    = image_tag 'logo-noice-wide.png', alt: 'NOICE', height: '25px'

  / Hamburguer to toggle menu
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  .collapse.navbar-collapse#navbarSupportedContent
    ul.navbar-nav.mx-auto
      - if user_signed_in?
        = form_tag('/search', class: "form-inline", method: "get")
          input.form-control.mr-sm-2 type="search" placeholder="Search" aria-label="Search" name="q"
          button.btn.btn-outline-light.my-2.my-sm-0 type="submit" Search
    ul.navbar-nav.my-2.my-lg-0
      - if user_signed_in?
        li.nav-item.dropdown
          a#navbarDropdown.nav-link.dropdown-toggle href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
            = current_user.email
          .dropdown-menu aria-labelledby="navbarDropdown"
            a.dropdown-item href="#" Profile
            / Only if admin
              a.dropdown-item href="#{tags_path}" Tags
            .dropdown-divider
            a.dropdown-item href="#{destroy_user_session_path}" data-method="delete" Sign out
      - else
        li.nav-item
          a.nav-link href="#{new_user_session_path}" Log in


- if user_signed_in?
  nav.navbar.navbar-expand-md.navbar-light.bg-light
    ul.navbar-nav.mx-auto
      / Sections
      li.nav-item
        a.nav-link href="#{questions_path}" Questions
      li.nav-item
        a.nav-link href="#{noice_sessions_path}" Sessions
      li.nav-item
        a.nav-link href="#{content_path}" Content
      li.nav-item
        a.nav-link href="#{events_path}" Events