config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  # Feedback
  resources :questions
  resources :answers, only: [:index, :create, :update]

  # Noice Sessions
  resources :noice_sessions

  scope 'admin' do
    resources :tags
  end

  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'content', to: 'pages#content', as: :content
  get 'events', to: 'pages#events', as: :events
  get 'search', to: 'pages#search', as: :search

  root to: redirect("http://unbouncepages.com/mynoice/")
end

app/models/noice_session.rb
class NoiceSession < ApplicationRecord
  belongs_to :user

  validates_presence_of :mic_data, :interface_data, :equipment_data
  validates_length_of :mic_data, in: 5..1000
  validates_length_of :interface_data, in: 5..1000
  validates_length_of :equipment_data, in: 5..1000

  enum status: [:waiting_diagnostics, :waiting_approval, :ongoing]

  def status_label
    return "Closed" unless self.open
    return "Waiting for diagnostics" if waiting_diagnostics?
    return "Waiting for member approval" if waiting_approval?
    return "Ongoing" if ongoing?
  end
end

app/controllers/noice_sessions_controller.rb
class NoiceSessionsController < ApplicationController
  before_action :set_noice_session, only: [:show, :edit, :update, :destroy]

  # GET /noice_sessions
  # GET /noice_sessions.json
  def index
    @noice_sessions = NoiceSession.all
  end

  # GET /noice_sessions/1
  # GET /noice_sessions/1.json
  def show
  end

  # GET /noice_sessions/new
  def new
    @noice_session = NoiceSession.new
  end

  # GET /noice_sessions/1/edit
  def edit
  end

  # POST /noice_sessions
  # POST /noice_sessions.json
  def create
    @noice_session = NoiceSession.new(noice_session_params)
    @noice_session.open = true
    @noice_session.status = :waiting_diagnostics
    @noice_session.user_id = current_user.id
    if @noice_session.save
      redirect_to @noice_session, notice: 'NoiceSession was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /noice_sessions/1
  # PATCH/PUT /noice_sessions/1.json
  def update
    if @noice_session.update(noice_session_params)
      redirect_to @noice_session, notice: 'NoiceSession was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /noice_sessions/1
  # DELETE /noice_sessions/1.json
  def destroy
    @noice_session.destroy
    redirect_to noice_sessions_url, notice: 'NoiceSession was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noice_session
      @noice_session = NoiceSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noice_session_params
      params.require(:noice_session).permit(:audio_file_url, :mic_data, :interface_data, :equipment_data)
    end
end

app/views/noice_sessions/_form.html.slim
= form_for @noice_session do |f|
  - if @noice_session.errors.any?
    = render 'form_errors', model: @noice_session

  .field.form-group
    = f.label :audio_file_url, "Sample audio file"
    = f.file_field :audio_file_url, class: "form-control", aria: { describedby: "audioFileUrlHelp" }
    small.form-text.text-muted#audioFileUrlHelp Please upload a recent, raw recording made on the space you'd like us to assess.
  .field.form-group
    = f.label :mic_data, "Microphone information"
    = f.text_area :mic_data, class: "form-control", aria: { describedby: "micDataHelp" }
    small.form-text.text-muted#micDataHelp Which microphone are you using? State reference, model, and how long have you been using it.
  .field.form-group
    = f.label :interface_data, "Interface information"
    = f.text_area :interface_data, class: "form-control", aria: { describedby: "interfaceDataHelp" }
    small.form-text.text-muted#interfaceDataHelp What interface are you using? State reference, model, and how long have you been using it. If you're using a USB microphone, please write USB.
  .field.form-group
    = f.label :equipment_data, "Equipment information"
    = f.text_area :equipment_data, class: "form-control", aria: { describedby: "equipmentDataHelp" }
    small.form-text.text-muted#equipmentDataHelp Please list any extra equipment you're using to record (i.e. preamplifiers, channel strips, compressors, etc.). State reference, model, and how long have you been using it. 

  .actions
    button.btn.btn-primary type="button" data-toggle="modal" data-target="#submitNoiceSessionModal" Submit

  / Model
  .modal.fade#submitNoiceSessionModal tabindex="-1" role="dialog" aria-labelledby="submitNoiceSessionModalLabel" aria-hidden="true"
    .modal-dialog role="document"
      .modal-content
        .modal-header
          h5.modal-title#submitNoiceSessionModalLabel Session Request
          button.close type="button" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true" &times;
        .modal-body
          p We're about to send your Session Request Form to our Diagnostics team. Do you confirm the information is correct?
        .modal-footer
          button.btn.btn-secondary type="button" data-dismiss="modal" No, come back
          = f.submit "Yes, I'm sure", class: "btn btn-primary"

 

app/views/noice_sessions/edit.html.slim
h1 Editing noice_session

== render 'form'

=> link_to 'Show', @noice_session
'|
=< link_to 'Back', noice_sessions_path

app/views/noice_sessions/index.html.slim
.row
  .col-sm-12.col-md-9
    h1 My Sessions
  .col-sm-12.col-md-3
    = link_to 'New Session', new_noice_session_path, class: "btn btn-primary btn-block"

.row
  .col-sm-12
    p In Noice Sessions, you as a member provide a set of recordings to be diagnosed and assessed by our experts aiming to get candid feedback and detailed solutions for your problems. Sessions are designed to be one-on-one conversations with a carefully chosen expert whose experience allows you to provide the most accurate feedback.

.row
  .col-sm-12
    ul.list-group
      - @noice_sessions.each do |noice_session|
        li.list-group-item
          .row
            .col-sm-12.col-md-8
              h3 = "Session ID #{noice_session.id}"
              i = "Modified #{noice_session.updated_at}"
              ul.nav
                li.nav-item
                  = link_to "View", noice_session, class: "nav-link"
            .col-sm-12.col-md-4
              p.status
                span.badge.badge-info = noice_session.status_label
              p.chats
                span.badge.badge-secondary> = noice_session.number_of_chats
                span> Chats
                - if noice_session.number_of_chats > 2
                  span.badge.badge-pill.badge-dark 🤓 Noooice!

app/views/noice_sessions/new.html.slim
h1 Request a session

p In order to get the best out of our Sessions experience, our Diagnostics team will process an assessment of your quality. For this, please fill in the following request.

== render 'form'

= link_to 'Back', noice_sessions_path

app/views/noice_sessions/show.html.slim
section role="noice_session"
  .jumbotron
    .row
      .col-sm-12.col-md-9
        h1.display-4 = "Session ID #{@noice_session.id}"
        hr.my-4
        / Audio Player
          .field-data
            h4 Recording
            #waveform
        .field-data
          h4 Microphone information:
          h5.card-subtitle.mb-2.text-muted Which microphone are you using? State reference, model, and how long have you been using it.
          p
            = @noice_session.mic_data
        .field-data
          h4 Interface information:
          h5.card-subtitle.mb-2.text-muted What interface are you using? State reference, model, and how long have you been using it. If you're using a USB microphone, please write USB.
          p
            = @noice_session.interface_data
        .field-data
          h4 Equipment information:
          h5.card-subtitle.mb-2.text-muted Please list any extra equipment you're using to record (i.e. preamplifiers, channel strips, compressors, etc.). State reference, model, and how long have you been using it.
          p
            = @noice_session.equipment_data
      .col-sm-12.col-md-3
        p.status
          span.badge.badge-info = @noice_session.status_label
        p.user
          span = @noice_session.user.email
        p.chats
          span.badge.badge-secondary> = @noice_session.number_of_chats
          span> Chats
          - if @noice_session.number_of_chats > 2
            span.badge.badge-pill.badge-dark 🤓 Noooice!